FROM maven:3.3.3-jdk-8
ENV BUILD_HOME=/tmp/build
RUN mkdir -p $BUILD_HOME
WORKDIR $BUILD_HOME

# selectively add the POM file
COPY pom.xml $BUILD_HOME
# get all the downloads out of the way - как-то не особо работает.
RUN mvn verify clean --fail-never

COPY . $BUILD_HOME
RUN mvn verify

#VOLUME ["/tmp/build/target"]